import { PDF_TOOLS } from './pdfTools';

export interface ToolResultConfig {
  toolId: string;
  slug: string;
  name: string;
  successTitle: string;
  downloadLabel: string;
  fileExtension: string;
  mimeType: string;
  relatedToolIds: string[];
}

export const TOOL_RESULTS_CONFIG: Record<string, ToolResultConfig> = {
  'merge-pdf': {
    toolId: 'merge-pdf',
    slug: '/merge-pdf',
    name: 'Merge PDF',
    successTitle: 'PDFs have been merged!',
    downloadLabel: 'Download merged PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['split-pdf', 'compress-pdf', 'organize-pdf', 'add-page-numbers', 'watermark', 'protect-pdf'],
  },
  'split-pdf': {
    toolId: 'split-pdf',
    slug: '/split-pdf',
    name: 'Split PDF',
    successTitle: 'Your PDF has been split!',
    downloadLabel: 'Download split PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['merge-pdf', 'compress-pdf', 'extract-pages', 'organize-pdf', 'rotate-pdf', 'protect-pdf'],
  },
  'compress-pdf': {
    toolId: 'compress-pdf',
    slug: '/compress-pdf',
    name: 'Compress PDF',
    successTitle: 'Your PDF has been compressed!',
    downloadLabel: 'Download compressed PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['merge-pdf', 'split-pdf', 'pdf-to-word', 'pdf-to-jpg', 'protect-pdf', 'edit-pdf'],
  },
  'pdf-to-word': {
    toolId: 'pdf-to-word',
    slug: '/pdf-to-word',
    name: 'PDF to Word',
    successTitle: 'Your Word document is ready!',
    downloadLabel: 'Download Word file',
    fileExtension: 'docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    relatedToolIds: ['word-to-pdf', 'edit-pdf', 'ocr-pdf', 'pdf-to-excel', 'pdf-to-txt', 'compress-pdf'],
  },
  'pdf-to-powerpoint': {
    toolId: 'pdf-to-powerpoint',
    slug: '/pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    successTitle: 'Your PowerPoint document is ready!',
    downloadLabel: 'Download PowerPoint file',
    fileExtension: 'pptx',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    relatedToolIds: ['powerpoint-to-pdf', 'pdf-to-word', 'compress-pdf', 'edit-pdf', 'merge-pdf', 'pdf-to-jpg'],
  },
  'pdf-to-excel': {
    toolId: 'pdf-to-excel',
    slug: '/pdf-to-excel',
    name: 'PDF to Excel',
    successTitle: 'Your Excel spreadsheet is ready!',
    downloadLabel: 'Download Excel file',
    fileExtension: 'xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    relatedToolIds: ['excel-to-pdf', 'pdf-to-word', 'ocr-pdf', 'extract-pdf-tables', 'compress-pdf', 'edit-pdf'],
  },
  'word-to-pdf': {
    toolId: 'word-to-pdf',
    slug: '/word-to-pdf',
    name: 'Word to PDF',
    successTitle: 'Your PDF is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['compress-pdf', 'merge-pdf', 'protect-pdf', 'pdf-to-word', 'add-page-numbers', 'edit-pdf'],
  },
  'powerpoint-to-pdf': {
    toolId: 'powerpoint-to-pdf',
    slug: '/powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    successTitle: 'Your PDF is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['compress-pdf', 'merge-pdf', 'protect-pdf', 'pdf-to-powerpoint', 'watermark', 'split-pdf'],
  },
  'excel-to-pdf': {
    toolId: 'excel-to-pdf',
    slug: '/excel-to-pdf',
    name: 'Excel to PDF',
    successTitle: 'Your PDF is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['compress-pdf', 'merge-pdf', 'protect-pdf', 'pdf-to-excel', 'add-page-numbers', 'edit-pdf'],
  },
  'edit-pdf': {
    toolId: 'edit-pdf',
    slug: '/edit-pdf',
    name: 'Edit PDF',
    successTitle: 'Your edited PDF is ready!',
    downloadLabel: 'Download edited PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['compress-pdf', 'sign-pdf', 'protect-pdf', 'watermark', 'add-page-numbers', 'merge-pdf'],
  },
  'pdf-to-jpg': {
    toolId: 'pdf-to-jpg',
    slug: '/pdf-to-jpg',
    name: 'PDF to JPG',
    successTitle: 'Your JPG files are ready!',
    downloadLabel: 'Download JPG files',
    fileExtension: 'jpg',
    mimeType: 'image/jpeg',
    relatedToolIds: ['jpg-to-pdf', 'compress-pdf', 'pdf-to-png', 'png-to-pdf', 'extract-pages', 'edit-pdf'],
  },
  'jpg-to-pdf': {
    toolId: 'jpg-to-pdf',
    slug: '/jpg-to-pdf',
    name: 'JPG to PDF',
    successTitle: 'Your PDF is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['compress-pdf', 'merge-pdf', 'edit-pdf', 'pdf-to-jpg', 'protect-pdf', 'add-page-numbers'],
  },
  'sign-pdf': {
    toolId: 'sign-pdf',
    slug: '/sign-pdf',
    name: 'Sign PDF',
    successTitle: 'Your signed PDF is ready!',
    downloadLabel: 'Download signed PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['protect-pdf', 'edit-pdf', 'compress-pdf', 'watermark', 'flatten-pdf', 'merge-pdf'],
  },
  'watermark': {
    toolId: 'watermark',
    slug: '/watermark-pdf',
    name: 'Watermark',
    successTitle: 'Your watermarked PDF is ready!',
    downloadLabel: 'Download watermarked PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['protect-pdf', 'add-page-numbers', 'edit-pdf', 'compress-pdf', 'merge-pdf', 'flatten-pdf'],
  },
  'rotate-pdf': {
    toolId: 'rotate-pdf',
    slug: '/rotate-pdf',
    name: 'Rotate PDF',
    successTitle: 'Your rotated PDF is ready!',
    downloadLabel: 'Download rotated PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['organize-pdf', 'merge-pdf', 'compress-pdf', 'crop-pdf', 'edit-pdf', 'protect-pdf'],
  },
  'html-to-pdf': {
    toolId: 'html-to-pdf',
    slug: '/html-to-pdf',
    name: 'HTML to PDF',
    successTitle: 'Your PDF is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['compress-pdf', 'edit-pdf', 'pdf-to-html', 'protect-pdf', 'add-page-numbers', 'merge-pdf'],
  },
  'unlock-pdf': {
    toolId: 'unlock-pdf',
    slug: '/unlock-pdf',
    name: 'Unlock PDF',
    successTitle: 'Your unlocked PDF is ready!',
    downloadLabel: 'Download unlocked PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['protect-pdf', 'compress-pdf', 'edit-pdf', 'merge-pdf', 'split-pdf', 'pdf-to-word'],
  },
  'protect-pdf': {
    toolId: 'protect-pdf',
    slug: '/protect-pdf',
    name: 'Protect PDF',
    successTitle: 'Your protected PDF is ready!',
    downloadLabel: 'Download protected PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['unlock-pdf', 'compress-pdf', 'sign-pdf', 'watermark', 'merge-pdf', 'flatten-pdf'],
  },
  'organize-pdf': {
    toolId: 'organize-pdf',
    slug: '/organize-pdf',
    name: 'Organize PDF',
    successTitle: 'Your PDF has been organized!',
    downloadLabel: 'Download organized PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['rotate-pdf', 'merge-pdf', 'split-pdf', 'remove-pages', 'extract-pages', 'compress-pdf'],
  },
  'pdf-to-pdfa': {
    toolId: 'pdf-to-pdfa',
    slug: '/pdf-to-pdfa',
    name: 'PDF to PDF/A',
    successTitle: 'Your PDF/A document is ready!',
    downloadLabel: 'Download PDF/A',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['compress-pdf', 'protect-pdf', 'repair-pdf', 'flatten-pdf', 'edit-pdf', 'merge-pdf'],
  },
  'repair-pdf': {
    toolId: 'repair-pdf',
    slug: '/repair-pdf',
    name: 'Repair PDF',
    successTitle: 'Your repaired PDF is ready!',
    downloadLabel: 'Download repaired PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['compress-pdf', 'unlock-pdf', 'ocr-pdf', 'edit-pdf', 'merge-pdf', 'organize-pdf'],
  },
  'add-page-numbers': {
    toolId: 'add-page-numbers',
    slug: '/add-page-numbers',
    name: 'Page numbers',
    successTitle: 'Your numbered PDF is ready!',
    downloadLabel: 'Download numbered PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['watermark', 'edit-pdf', 'compress-pdf', 'merge-pdf', 'protect-pdf', 'organize-pdf'],
  },
  'scan-to-pdf': {
    toolId: 'scan-to-pdf',
    slug: '/scan-to-pdf',
    name: 'Scan to PDF',
    successTitle: 'Your PDF scan is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['ocr-pdf', 'compress-pdf', 'crop-pdf', 'edit-pdf', 'pdf-to-word', 'merge-pdf'],
  },
  'ocr-pdf': {
    toolId: 'ocr-pdf',
    slug: '/ocr-pdf',
    name: 'OCR PDF',
    successTitle: 'Your searchable PDF is ready!',
    downloadLabel: 'Download searchable PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['pdf-to-word', 'pdf-to-excel', 'pdf-to-txt', 'ai-pdf-summarizer', 'translate-pdf', 'compress-pdf'],
  },
  'compare-pdf': {
    toolId: 'compare-pdf',
    slug: '/compare-pdf',
    name: 'Compare PDF',
    successTitle: 'Your PDF comparison is ready!',
    downloadLabel: 'Download PDF comparison',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['edit-pdf', 'redact-pdf', 'compress-pdf', 'merge-pdf', 'protect-pdf', 'annotate-pdf'],
  },
  'redact-pdf': {
    toolId: 'redact-pdf',
    slug: '/redact-pdf',
    name: 'Redact PDF',
    successTitle: 'Your redacted PDF is ready!',
    downloadLabel: 'Download redacted PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['protect-pdf', 'remove-metadata', 'flatten-pdf', 'edit-pdf', 'compress-pdf', 'sign-pdf'],
  },
  'crop-pdf': {
    toolId: 'crop-pdf',
    slug: '/crop-pdf',
    name: 'Crop PDF',
    successTitle: 'Your cropped PDF is ready!',
    downloadLabel: 'Download cropped PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['rotate-pdf', 'compress-pdf', 'edit-pdf', 'organize-pdf', 'watermark', 'add-page-numbers'],
  },
  'pdf-forms': {
    toolId: 'pdf-forms',
    slug: '/pdf-forms',
    name: 'PDF Forms',
    successTitle: 'Your PDF form is ready!',
    downloadLabel: 'Download PDF form',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['flatten-pdf', 'sign-pdf', 'edit-pdf', 'protect-pdf', 'compress-pdf', 'merge-pdf'],
  },
  'ai-pdf-summarizer': {
    toolId: 'ai-pdf-summarizer',
    slug: '/ai-pdf-summarizer',
    name: 'AI Summarizer',
    successTitle: 'Your PDF summary is ready!',
    downloadLabel: 'Download summary',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['translate-pdf', 'pdf-to-markdown', 'pdf-to-word', 'pdf-question-answer', 'extract-pdf-text', 'ocr-pdf'],
  },
  'translate-pdf': {
    toolId: 'translate-pdf',
    slug: '/translate-pdf',
    name: 'Translate PDF',
    successTitle: 'Your translated PDF is ready!',
    downloadLabel: 'Download translated PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['ai-pdf-summarizer', 'pdf-to-word', 'ocr-pdf', 'edit-pdf', 'compress-pdf', 'pdf-to-txt'],
  },
  'pdf-to-markdown': {
    toolId: 'pdf-to-markdown',
    slug: '/pdf-to-markdown',
    name: 'PDF to Markdown',
    successTitle: 'Your Markdown file is ready!',
    downloadLabel: 'Download Markdown file',
    fileExtension: 'md',
    mimeType: 'text/markdown',
    relatedToolIds: ['pdf-to-txt', 'pdf-to-word', 'ai-pdf-summarizer', 'extract-pdf-text', 'ocr-pdf', 'compress-pdf'],
  },
  'remove-pages': {
    toolId: 'remove-pages',
    slug: '/remove-pages',
    name: 'Remove Pages',
    successTitle: 'Your PDF is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['extract-pages', 'organize-pdf', 'split-pdf', 'merge-pdf', 'compress-pdf', 'rotate-pdf'],
  },
  'extract-pages': {
    toolId: 'extract-pages',
    slug: '/extract-pages',
    name: 'Extract Pages',
    successTitle: 'Your extracted pages are ready!',
    downloadLabel: 'Download extracted PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['split-pdf', 'remove-pages', 'merge-pdf', 'organize-pdf', 'compress-pdf', 'pdf-to-word'],
  },
  'png-to-pdf': {
    toolId: 'png-to-pdf',
    slug: '/png-to-pdf',
    name: 'PNG to PDF',
    successTitle: 'Your PDF is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['jpg-to-pdf', 'compress-pdf', 'merge-pdf', 'edit-pdf', 'pdf-to-png', 'protect-pdf'],
  },
  'pdf-to-png': {
    toolId: 'pdf-to-png',
    slug: '/pdf-to-png',
    name: 'PDF to PNG',
    successTitle: 'Your PNG files are ready!',
    downloadLabel: 'Download PNG files',
    fileExtension: 'zip',
    mimeType: 'application/zip',
    relatedToolIds: ['png-to-pdf', 'pdf-to-jpg', 'compress-pdf', 'extract-pages', 'edit-pdf', 'split-pdf'],
  },
  'pdf-to-txt': {
    toolId: 'pdf-to-txt',
    slug: '/pdf-to-txt',
    name: 'PDF to TXT',
    successTitle: 'Your TXT file is ready!',
    downloadLabel: 'Download TXT file',
    fileExtension: 'txt',
    mimeType: 'text/plain',
    relatedToolIds: ['txt-to-pdf', 'pdf-to-markdown', 'pdf-to-word', 'extract-pdf-text', 'ocr-pdf', 'ai-pdf-summarizer'],
  },
  'txt-to-pdf': {
    toolId: 'txt-to-pdf',
    slug: '/txt-to-pdf',
    name: 'TXT to PDF',
    successTitle: 'Your PDF is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['word-to-pdf', 'compress-pdf', 'edit-pdf', 'protect-pdf', 'add-page-numbers', 'merge-pdf'],
  },
  'pdf-to-html': {
    toolId: 'pdf-to-html',
    slug: '/pdf-to-html',
    name: 'PDF to HTML',
    successTitle: 'Your HTML file is ready!',
    downloadLabel: 'Download HTML file',
    fileExtension: 'html',
    mimeType: 'text/html',
    relatedToolIds: ['html-to-pdf', 'pdf-to-word', 'pdf-to-markdown', 'compress-pdf', 'edit-pdf', 'extract-pdf-text'],
  },
  'remove-metadata': {
    toolId: 'remove-metadata',
    slug: '/remove-pdf-metadata',
    name: 'Remove Metadata',
    successTitle: 'Your cleaned PDF is ready!',
    downloadLabel: 'Download cleaned PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['redact-pdf', 'flatten-pdf', 'protect-pdf', 'compress-pdf', 'edit-pdf', 'unlock-pdf'],
  },
  'flatten-pdf': {
    toolId: 'flatten-pdf',
    slug: '/flatten-pdf',
    name: 'Flatten PDF',
    successTitle: 'Your flattened PDF is ready!',
    downloadLabel: 'Download flattened PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['protect-pdf', 'sign-pdf', 'pdf-forms', 'redact-pdf', 'compress-pdf', 'watermark'],
  },
  'extract-pdf-text': {
    toolId: 'extract-pdf-text',
    slug: '/extract-pdf-text',
    name: 'Extract PDF Text',
    successTitle: 'Your extracted text is ready!',
    downloadLabel: 'Download text file',
    fileExtension: 'txt',
    mimeType: 'text/plain',
    relatedToolIds: ['pdf-to-txt', 'pdf-to-word', 'ai-pdf-summarizer', 'ocr-pdf', 'pdf-to-markdown', 'translate-pdf'],
  },
  'pdf-question-answer': {
    toolId: 'pdf-question-answer',
    slug: '/pdf-question-answer',
    name: 'PDF Question & Answer',
    successTitle: 'Your PDF Q&A report is ready!',
    downloadLabel: 'Download Q&A report',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['ai-pdf-summarizer', 'translate-pdf', 'pdf-to-word', 'ocr-pdf', 'extract-pdf-text', 'compress-pdf'],
  },
  'extract-pdf-tables': {
    toolId: 'extract-pdf-tables',
    slug: '/extract-pdf-tables',
    name: 'Extract PDF Tables',
    successTitle: 'Your extracted tables are ready!',
    downloadLabel: 'Download Excel file',
    fileExtension: 'xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    relatedToolIds: ['pdf-to-excel', 'ocr-pdf', 'pdf-to-word', 'extract-pdf-text', 'compress-pdf', 'edit-pdf'],
  },
  'annotate-pdf': {
    toolId: 'annotate-pdf',
    slug: '/annotate-pdf',
    name: 'Annotate PDF',
    successTitle: 'Your annotated PDF is ready!',
    downloadLabel: 'Download annotated PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['edit-pdf', 'watermark', 'protect-pdf', 'compress-pdf'],
  }
};

export function getToolResultConfig(toolIdOrSlug: string): ToolResultConfig {
  const cleanKey = toolIdOrSlug.replace(/^\//, '');
  
  if (TOOL_RESULTS_CONFIG[cleanKey]) {
    return TOOL_RESULTS_CONFIG[cleanKey];
  }

  // Find by slug match
  const foundBySlug = Object.values(TOOL_RESULTS_CONFIG).find(
    (c) => c.slug === toolIdOrSlug || c.slug === `/${cleanKey}`
  );

  if (foundBySlug) {
    return foundBySlug;
  }

  // Fallback default config
  return {
    toolId: cleanKey,
    slug: `/${cleanKey}`,
    name: cleanKey.replace(/-/g, ' ').toUpperCase(),
    successTitle: 'Your PDF is ready!',
    downloadLabel: 'Download PDF',
    fileExtension: 'pdf',
    mimeType: 'application/pdf',
    relatedToolIds: ['merge-pdf', 'split-pdf', 'compress-pdf', 'pdf-to-word', 'edit-pdf', 'protect-pdf'],
  };
}
