export type WorkspaceType = 
  | 'document-grid'  // Grid of uploaded file cards (Merge, Compress, JPG to PDF, etc.)
  | 'page-grid'      // Grid of individual page thumbnails (Split, Organize, Remove, Extract, Rotate)
  | 'single-preview' // Full page document view with interactive overlay (Crop, Watermark, Sign, Edit, Redact, Form)
  | 'dual-preview';  // Side-by-side document compare (Compare PDF)

export type OutputFileType = 'pdf' | 'docx' | 'xlsx' | 'pptx' | 'jpg' | 'png' | 'zip' | 'txt' | 'md' | 'json';

export interface ToolConfigSchema {
  id: string;
  title: string;
  slug: string;
  acceptedFileTypes: string[];
  multiple: boolean;
  minFiles: number;
  workspaceType: WorkspaceType;
  primaryButtonText: string;
  processingMessage: string;
  outputType: OutputFileType;
  description: string;
}

export const TOOL_CONFIGURATIONS: Record<string, ToolConfigSchema> = {
  'merge-pdf': {
    id: 'merge-pdf',
    title: 'Merge PDF',
    slug: '/merge-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: true,
    minFiles: 2,
    workspaceType: 'document-grid',
    primaryButtonText: 'Merge PDF →',
    processingMessage: 'Merging PDF files...',
    outputType: 'pdf',
    description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
  },

  'split-pdf': {
    id: 'split-pdf',
    title: 'Split PDF',
    slug: '/split-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'page-grid',
    primaryButtonText: 'Split PDF →',
    processingMessage: 'Splitting PDF document...',
    outputType: 'pdf',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
  },

  'compress-pdf': {
    id: 'compress-pdf',
    title: 'Compress PDF',
    slug: '/compress-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: true,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Compress PDF →',
    processingMessage: 'Compressing PDF files...',
    outputType: 'pdf',
    description: 'Reduce file size while optimizing for maximal PDF quality.',
  },

  'pdf-to-word': {
    id: 'pdf-to-word',
    title: 'PDF to Word',
    slug: '/pdf-to-word',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to WORD →',
    processingMessage: 'Converting PDF to Word document...',
    outputType: 'docx',
    description: 'Easily convert your PDF files into easy to edit DOC and DOCX documents.',
  },

  'pdf-to-powerpoint': {
    id: 'pdf-to-powerpoint',
    title: 'PDF to PowerPoint',
    slug: '/pdf-to-powerpoint',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to POWERPOINT →',
    processingMessage: 'Converting PDF to PowerPoint slideshow...',
    outputType: 'pptx',
    description: 'Turn your PDF files into easy to edit PPT and PPTX slideshows.',
  },

  'pdf-to-excel': {
    id: 'pdf-to-excel',
    title: 'PDF to Excel',
    slug: '/pdf-to-excel',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to EXCEL →',
    processingMessage: 'Converting PDF to Excel spreadsheet...',
    outputType: 'xlsx',
    description: 'Pull data straight from PDFs into Excel spreadsheets in a few short seconds.',
  },

  'word-to-pdf': {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    slug: '/word-to-pdf',
    acceptedFileTypes: ['.doc', '.docx', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to PDF →',
    processingMessage: 'Converting Word document to PDF...',
    outputType: 'pdf',
    description: 'Make DOC and DOCX files easy to read by converting them to PDF.',
  },

  'powerpoint-to-pdf': {
    id: 'powerpoint-to-pdf',
    title: 'PowerPoint to PDF',
    slug: '/powerpoint-to-pdf',
    acceptedFileTypes: ['.ppt', '.pptx', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to PDF →',
    processingMessage: 'Converting PowerPoint presentation to PDF...',
    outputType: 'pdf',
    description: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
  },

  'excel-to-pdf': {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    slug: '/excel-to-pdf',
    acceptedFileTypes: ['.xls', '.xlsx', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to PDF →',
    processingMessage: 'Converting Excel spreadsheet to PDF...',
    outputType: 'pdf',
    description: 'Make EXCEL spreadsheets easy to read by converting them to PDF.',
  },

  'edit-pdf': {
    id: 'edit-pdf',
    title: 'Edit PDF',
    slug: '/edit-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Edit PDF →',
    processingMessage: 'Saving edited PDF document...',
    outputType: 'pdf',
    description: 'Add text, images, shapes or freehand annotations to a PDF document.',
  },

  'pdf-to-jpg': {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    slug: '/pdf-to-jpg',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'page-grid',
    primaryButtonText: 'Convert to JPG →',
    processingMessage: 'Converting PDF pages to JPG images...',
    outputType: 'jpg',
    description: 'Convert each PDF page into a JPG or extract all images contained in a PDF.',
  },

  'jpg-to-pdf': {
    id: 'jpg-to-pdf',
    title: 'JPG to PDF',
    slug: '/jpg-to-pdf',
    acceptedFileTypes: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp', '.jpg', '.jpeg', '.png', '.webp'],
    multiple: true,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to PDF →',
    processingMessage: 'Converting images to PDF...',
    outputType: 'pdf',
    description: 'Adjust orientation and margins. Convert JPG images to PDF in seconds.',
  },

  'png-to-pdf': {
    id: 'png-to-pdf',
    title: 'PNG to PDF',
    slug: '/png-to-pdf',
    acceptedFileTypes: ['image/png', '.png', 'image/jpeg', '.jpg'],
    multiple: true,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to PDF →',
    processingMessage: 'Converting PNG images to PDF...',
    outputType: 'pdf',
    description: 'Convert PNG images to PDF documents easily.',
  },

  'pdf-to-png': {
    id: 'pdf-to-png',
    title: 'PDF to PNG',
    slug: '/pdf-to-png',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'page-grid',
    primaryButtonText: 'Convert to PNG →',
    processingMessage: 'Converting PDF pages to PNG images...',
    outputType: 'png',
    description: 'Extract images or save PDF pages as PNG files.',
  },

  'sign-pdf': {
    id: 'sign-pdf',
    title: 'Sign PDF',
    slug: '/sign-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Sign PDF →',
    processingMessage: 'Applying signature to PDF...',
    outputType: 'pdf',
    description: 'Sign yourself or request electronic signatures from others.',
  },

  'watermark': {
    id: 'watermark',
    title: 'Watermark PDF',
    slug: '/watermark-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Add watermark →',
    processingMessage: 'Stamping watermark on PDF...',
    outputType: 'pdf',
    description: 'Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.',
  },

  'rotate-pdf': {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    slug: '/rotate-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: true,
    minFiles: 1,
    workspaceType: 'page-grid',
    primaryButtonText: 'Rotate PDF →',
    processingMessage: 'Rotating PDF pages...',
    outputType: 'pdf',
    description: 'Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!',
  },

  'unlock-pdf': {
    id: 'unlock-pdf',
    title: 'Unlock PDF',
    slug: '/unlock-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Unlock PDF →',
    processingMessage: 'Decrypting PDF security...',
    outputType: 'pdf',
    description: 'Remove PDF password security, giving you the freedom to use your PDFs as you want.',
  },

  'protect-pdf': {
    id: 'protect-pdf',
    title: 'Protect PDF',
    slug: '/protect-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Protect PDF →',
    processingMessage: 'Encrypting PDF with password...',
    outputType: 'pdf',
    description: 'Encrypt your PDF with a password to keep sensitive data confidential.',
  },

  'organize-pdf': {
    id: 'organize-pdf',
    title: 'Organize PDF',
    slug: '/organize-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: true,
    minFiles: 1,
    workspaceType: 'page-grid',
    primaryButtonText: 'Organize PDF →',
    processingMessage: 'Organizing PDF pages...',
    outputType: 'pdf',
    description: 'Sort, add and delete PDF pages. Drag and drop the page thumbnails and sort them in our PDF organizer.',
  },

  'remove-pages': {
    id: 'remove-pages',
    title: 'Remove Pages',
    slug: '/remove-pages',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'page-grid',
    primaryButtonText: 'Remove pages →',
    processingMessage: 'Deleting selected pages...',
    outputType: 'pdf',
    description: 'Delete selected pages from your PDF document.',
  },

  'extract-pages': {
    id: 'extract-pages',
    title: 'Extract Pages',
    slug: '/extract-pages',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'page-grid',
    primaryButtonText: 'Extract pages →',
    processingMessage: 'Extracting pages from PDF...',
    outputType: 'pdf',
    description: 'Get a new document containing only the pages you need.',
  },

  'crop-pdf': {
    id: 'crop-pdf',
    title: 'Crop PDF',
    slug: '/crop-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Crop PDF →',
    processingMessage: 'Cropping PDF margins...',
    outputType: 'pdf',
    description: 'Crop PDF to a selected area, adjust margin size, and remove white margins.',
  },

  'add-page-numbers': {
    id: 'add-page-numbers',
    title: 'Add Page Numbers',
    slug: '/add-page-numbers',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Add page numbers →',
    processingMessage: 'Inserting page numbers...',
    outputType: 'pdf',
    description: 'Add page numbers into PDFs with ease. Choose your positions, dimensions, typography.',
  },

  'pdf-to-pdfa': {
    id: 'pdf-to-pdfa',
    title: 'PDF to PDF/A',
    slug: '/pdf-to-pdfa',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to PDF/A →',
    processingMessage: 'Converting PDF to PDF/A standard...',
    outputType: 'pdf',
    description: 'Transform your PDF to PDF/A, the ISO-standardized version of PDF for long-term archiving.',
  },

  'repair-pdf': {
    id: 'repair-pdf',
    title: 'Repair PDF',
    slug: '/repair-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Repair PDF →',
    processingMessage: 'Rebuilding corrupt PDF structure...',
    outputType: 'pdf',
    description: 'Repair a damaged PDF and recover data from corrupt PDF. Fix PDF files with our Repair tool.',
  },

  'scan-to-pdf': {
    id: 'scan-to-pdf',
    title: 'Scan to PDF',
    slug: '/scan-to-pdf',
    acceptedFileTypes: ['image/jpeg', 'image/png', '.jpg', '.png'],
    multiple: true,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Create PDF →',
    processingMessage: 'Building PDF from document scans...',
    outputType: 'pdf',
    description: 'Capture document scans from your mobile device and send them instantly to your browser.',
  },

  'ocr-pdf': {
    id: 'ocr-pdf',
    title: 'OCR PDF',
    slug: '/ocr-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Run OCR →',
    processingMessage: 'Recognizing text via OCR...',
    outputType: 'pdf',
    description: 'Convert PDF scans to searchable text and select. Recognize text in any PDF document with OCR.',
  },

  'compare-pdf': {
    id: 'compare-pdf',
    title: 'Compare PDF',
    slug: '/compare-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: true,
    minFiles: 2,
    workspaceType: 'dual-preview',
    primaryButtonText: 'Compare PDFs →',
    processingMessage: 'Analyzing document differences...',
    outputType: 'pdf',
    description: 'Quickly find the differences between two PDFs. Visually compare two documents side by side.',
  },

  'redact-pdf': {
    id: 'redact-pdf',
    title: 'Redact PDF',
    slug: '/redact-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Apply Redactions →',
    processingMessage: 'Permanently removing sensitive data...',
    outputType: 'pdf',
    description: 'Permanently remove visible text and graphics from a document to protect sensitive information.',
  },

  'pdf-forms': {
    id: 'pdf-forms',
    title: 'PDF Forms',
    slug: '/pdf-forms',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Create PDF Form →',
    processingMessage: 'Adding interactive form fields...',
    outputType: 'pdf',
    description: 'Create fillable PDF forms or fill existing ones easily online.',
  },

  'ai-pdf-summarizer': {
    id: 'ai-pdf-summarizer',
    title: 'AI Summarizer',
    slug: '/ai-pdf-summarizer',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Summarize PDF →',
    processingMessage: 'Generating AI summary...',
    outputType: 'txt',
    description: 'Get quick summaries of your PDF documents using advanced AI technology.',
  },

  'translate-pdf': {
    id: 'translate-pdf',
    title: 'Translate PDF',
    slug: '/translate-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Translate PDF →',
    processingMessage: 'Translating PDF document...',
    outputType: 'pdf',
    description: 'Translate your PDF into any language while maintaining the original layout.',
  },

  'pdf-to-markdown': {
    id: 'pdf-to-markdown',
    title: 'PDF to Markdown',
    slug: '/pdf-to-markdown',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to Markdown →',
    processingMessage: 'Extracting content to Markdown...',
    outputType: 'md',
    description: 'Extract text and structure into standard Markdown format.',
  },

  'html-to-pdf': {
    id: 'html-to-pdf',
    title: 'HTML to PDF',
    slug: '/html-to-pdf',
    acceptedFileTypes: ['.html', '.htm', 'text/html'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to PDF →',
    processingMessage: 'Rendering HTML page to PDF...',
    outputType: 'pdf',
    description: 'Convert webpages in HTML to PDF. Copy and paste the URL or upload HTML.',
  },

  'pdf-to-txt': {
    id: 'pdf-to-txt',
    title: 'PDF to TXT',
    slug: '/pdf-to-txt',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to TXT →',
    processingMessage: 'Extracting plain text...',
    outputType: 'txt',
    description: 'Extract raw text from your PDF into a TXT file.',
  },

  'txt-to-pdf': {
    id: 'txt-to-pdf',
    title: 'TXT to PDF',
    slug: '/txt-to-pdf',
    acceptedFileTypes: ['.txt', 'text/plain'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to PDF →',
    processingMessage: 'Converting text file to PDF...',
    outputType: 'pdf',
    description: 'Convert plain text files into professional PDF documents.',
  },

  'pdf-to-html': {
    id: 'pdf-to-html',
    title: 'PDF to HTML',
    slug: '/pdf-to-html',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Convert to HTML →',
    processingMessage: 'Converting PDF to HTML page...',
    outputType: 'txt',
    description: 'Convert your PDF documents into HTML web pages.',
  },

  'remove-metadata': {
    id: 'remove-metadata',
    title: 'Remove Metadata',
    slug: '/remove-pdf-metadata',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Remove Metadata →',
    processingMessage: 'Cleaning document metadata...',
    outputType: 'pdf',
    description: 'Clean your PDF files of hidden data and metadata.',
  },

  'flatten-pdf': {
    id: 'flatten-pdf',
    title: 'Flatten PDF',
    slug: '/flatten-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Flatten PDF →',
    processingMessage: 'Flattening forms and annotations...',
    outputType: 'pdf',
    description: 'Flatten fillable forms and annotations into a single non-editable layer.',
  },

  'extract-pdf-text': {
    id: 'extract-pdf-text',
    title: 'Extract PDF Text',
    slug: '/extract-pdf-text',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Extract Text →',
    processingMessage: 'Extracting text content...',
    outputType: 'txt',
    description: 'Pull all text content from a PDF document for easy reuse.',
  },

  'extract-pdf-tables': {
    id: 'extract-pdf-tables',
    title: 'Extract PDF Tables',
    slug: '/extract-pdf-tables',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Extract Tables →',
    processingMessage: 'Detecting and extracting tables...',
    outputType: 'xlsx',
    description: 'Intelligently detect and extract tables from PDFs to CSV or Excel.',
  },

  'annotate-pdf': {
    id: 'annotate-pdf',
    title: 'Annotate PDF',
    slug: '/annotate-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Save Annotations →',
    processingMessage: 'Saving annotations...',
    outputType: 'pdf',
    description: 'Add notes, comments, and highlights to your PDF.',
  },

  'add-text-pdf': {
    id: 'add-text-pdf',
    title: 'Add Text to PDF',
    slug: '/add-text-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Add Text →',
    processingMessage: 'Applying text overlays...',
    outputType: 'pdf',
    description: 'Type new text directly onto your PDF pages.',
  },

  'add-image-pdf': {
    id: 'add-image-pdf',
    title: 'Add Image to PDF',
    slug: '/add-image-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Insert Image →',
    processingMessage: 'Inserting image onto PDF...',
    outputType: 'pdf',
    description: 'Insert images, logos or pictures into your document.',
  },

  'draw-on-pdf': {
    id: 'draw-on-pdf',
    title: 'Draw on PDF',
    slug: '/draw-on-pdf',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'single-preview',
    primaryButtonText: 'Save Drawing →',
    processingMessage: 'Saving drawings to PDF...',
    outputType: 'pdf',
    description: 'Use freehand drawing tools directly on your PDF pages.',
  },

  'pdf-question-answer': {
    id: 'pdf-question-answer',
    title: 'PDF Question & Answer',
    slug: '/pdf-question-answer',
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: false,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: 'Chat with PDF →',
    processingMessage: 'Analyzing PDF content...',
    outputType: 'txt',
    description: 'Chat with your PDF and ask questions using AI.',
  },
};

export const getToolConfig = (idOrSlug: string): ToolConfigSchema => {
  if (TOOL_CONFIGURATIONS[idOrSlug]) return TOOL_CONFIGURATIONS[idOrSlug];
  const found = Object.values(TOOL_CONFIGURATIONS).find(
    c => c.slug === idOrSlug || c.id === idOrSlug || c.slug === `/${idOrSlug}`
  );
  if (found) return found;

  // Fallback schema
  const cleanId = idOrSlug.replace(/^\//, '');
  const title = cleanId.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
  return {
    id: cleanId,
    title,
    slug: `/${cleanId}`,
    acceptedFileTypes: ['application/pdf', '.pdf'],
    multiple: true,
    minFiles: 1,
    workspaceType: 'document-grid',
    primaryButtonText: `${title} →`,
    processingMessage: `Processing ${title}...`,
    outputType: 'pdf',
    description: `Process your PDF with ${title}.`,
  };
};
